name: Deploy using Github Action
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: build
      - name: Simple Github Pages Deployment
        uses: abdulkhlequegithub/simple-github-pages-deployment@afe4f6e4cd84f5b63890cb716c03640e84b68df9
        with:
          username: abdulkhalequegithub
          reponame: afe4f6e4cd84f5b63890cb716c03640e84b68df9
          token: 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