name: Deploy using Github Action
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: build
      - name: Push changes
        uses: ptienchuan/deploy-github-pages-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITTOKEN }}
        with:
          folder: build
          target-branch: "gh-pages"
          user-name: "abdulkhalequegithub"
          user-email: "abdul.khaleque@clouddrove.com"